export { Hero } from "./Hero";
export { IndustrySlider } from "./Industry";
export { AboutUsSection } from "./About";
export { ClinteSlider } from "./Clinte"
export { StatisticsSection } from "./Why"
export { AboutTheFounder } from "./AboutFounder"
export { WiseSolutionsIndustry } from "./InsdustrySolution"
export { ContactForm } from "./ContactForm"
export { CustomerTestimonials } from "./Testimonials"